In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/Bl3f/amse2021/main/Homework/hebergements_classes.csv'
df = pd.read_csv(url, sep = ";")

In [3]:
df.head(10)

DATE DE CLASSEMENT TYPOLOGIE ÉTABLISSEMENT CLASSEMENT CATÉGORIE  \
0         18/10/2018       HÔTEL DE TOURISME  4 étoiles         -   
1         26/09/2019       HÔTEL DE TOURISME  2 étoiles         -   
2         12/06/2017       HÔTEL DE TOURISME  4 étoiles         -   
3         22/09/2017       HÔTEL DE TOURISME  4 étoiles         -   
4         29/11/2019       HÔTEL DE TOURISME  3 étoiles         -   
5         27/09/2019       HÔTEL DE TOURISME  3 étoiles         -   
6         13/07/2016       HÔTEL DE TOURISME  3 étoiles         -   
7         21/12/2015       HÔTEL DE TOURISME  4 étoiles         -   
8         31/10/2017       HÔTEL DE TOURISME  4 étoiles         -   
9         07/06/2017       HÔTEL DE TOURISME  4 étoiles         -   

  MENTION (villages de vacances)                            NOM COMMERCIAL  \
0                              -                        1872 STADIUM HÔTEL   
1                              -                      3B HÔTEL DE BORDEAUX   
2                              -  5 TERRES HÔTEL & SPA MGALLERY BY SOFITEL   
3                              -                                7HÔTEL&SPA   
4                              -                     9 HÔTEL BASTILLE LYON   
5                              -                      9 HÔTEL MONTPARNASSE   
6                              -                              9HÔTEL OPÉRA   
7                              -                         9HÔTEL RÉPUBLIQUE   
8                              -                    ABBAYE DE SAINTE CROIX   
9                              -                       ABBAYE DE TALLOIRES   

                          ADRESSE CODE POSTAL                   COMMUNE  \
0          Boulevard de Leningrad       76600                  LE HAVRE   
1      66 avenue de la Libération       33440        AMBARÈS-ET-LAGRAVE   
2    11 Place de l'Hôtel de ville       67140                      BARR   
3  550 Boulevard Sébastien Brandt       67400    ILLKIRCH-GRAFFENSTADEN   
4                  23 rue de lyon       75012                     PARIS   
5        76 rue Raymond Losserand       75014  PARIS 14E ARRONDISSEMENT   
6                 14 rue Papillon       75009                     PARIS   
7         7/9 Rue Pierre Chausson       75010                     PARIS   
8           route du Val de Cuech       13300         SALON-DE-PROVENCE   
9               chemin des Moines       74290                 TALLOIRES   

                                     SITE INTERNET TYPE DE SÉJOUR  \
0             https://www.1872stadiumhotel.com/fr/              -   
1         https://www.hotel-restaurant-gironde.fr/              -   
2                     https://5terres-hotel.fr/fr/              -   
3                               https://7hotel.fr/              -   
4             https://www.9-hotel-bastille-lyon.fr              -   
5    https://www.9-hotel-montparnasse-paris.fr/fr/              -   
6       http://www.le9hotel.com/fr/h/9-hotel-opera              -   
7  http://www.le9hotel.com/fr/h/9-hotel-republique              -   
8             http://www.abbaye-de-saintecroix.fr/              -   
9                         www.abbaye-talloires.com              -   

  CAPACITÉ D'ACCUEIL (PERSONNES) NOMBRE DE CHAMBRES NOMBRE D'EMPLACEMENTS  \
0                             40                 20                     -   
1                             26                 14                     -   
2                             56                 27                     -   
3                            312                139                     -   
4                             90                 48                     -   
5                             86                 43                     -   
6                             91                 48                     -   
7                             92                 48                     -   
8                             61                 25                     -   
9                          

In [4]:
df.shape

(21326, 16)

In [5]:
num_missing = (df[["TYPOLOGIE ÉTABLISSEMENT","CLASSEMENT", "NOM COMMERCIAL", "CAPACITÉ D'ACCUEIL (PERSONNES)", "NOMBRE DE CHAMBRES", "NOMBRE D'EMPLACEMENTS", "NOMBRE D'UNITES D'HABITATION (résidences de tourisme)", "NOMBRE DE LOGEMENTS (villages de vacances)"]] == "-").sum()/len(df)
print(num_missing)

TYPOLOGIE ÉTABLISSEMENT                                  0.000000
CLASSEMENT                                               0.000000
NOM COMMERCIAL                                           0.000000
CAPACITÉ D'ACCUEIL (PERSONNES)                           0.001032
NOMBRE DE CHAMBRES                                       0.386336
NOMBRE D'EMPLACEMENTS                                    0.711760
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)    0.927319
NOMBRE DE LOGEMENTS (villages de vacances)               0.974679
dtype: float64


In [6]:
df.dtypes

DATE DE CLASSEMENT                                       object
TYPOLOGIE ÉTABLISSEMENT                                  object
CLASSEMENT                                               object
CATÉGORIE                                                object
MENTION (villages de vacances)                           object
NOM COMMERCIAL                                           object
ADRESSE                                                  object
CODE POSTAL                                              object
COMMUNE                                                  object
SITE INTERNET                                            object
TYPE DE SÉJOUR                                           object
CAPACITÉ D'ACCUEIL (PERSONNES)                           object
NOMBRE DE CHAMBRES                                       object
NOMBRE D'EMPLACEMENTS                                    object
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)    object
NOMBRE DE LOGEMENTS (villages de vacance

In [7]:
df.replace('-', np.NaN, inplace=True)

In [8]:
df.drop( df[ df["CAPACITÉ D'ACCUEIL (PERSONNES)"].isnull() ].index , inplace=True)

In [9]:
df.isnull().sum()

DATE DE CLASSEMENT                                           0
TYPOLOGIE ÉTABLISSEMENT                                      0
CLASSEMENT                                                   0
CATÉGORIE                                                15357
MENTION (villages de vacances)                           21074
NOM COMMERCIAL                                               0
ADRESSE                                                      0
CODE POSTAL                                                  1
COMMUNE                                                     15
SITE INTERNET                                              294
TYPE DE SÉJOUR                                           20764
CAPACITÉ D'ACCUEIL (PERSONNES)                               0
NOMBRE DE CHAMBRES                                        8223
NOMBRE D'EMPLACEMENTS                                    15168
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)    19755
NOMBRE DE LOGEMENTS (villages de vacances)             

In [10]:
df.dtypes

DATE DE CLASSEMENT                                       object
TYPOLOGIE ÉTABLISSEMENT                                  object
CLASSEMENT                                               object
CATÉGORIE                                                object
MENTION (villages de vacances)                           object
NOM COMMERCIAL                                           object
ADRESSE                                                  object
CODE POSTAL                                              object
COMMUNE                                                  object
SITE INTERNET                                            object
TYPE DE SÉJOUR                                           object
CAPACITÉ D'ACCUEIL (PERSONNES)                           object
NOMBRE DE CHAMBRES                                       object
NOMBRE D'EMPLACEMENTS                                    object
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)    object
NOMBRE DE LOGEMENTS (villages de vacance

In [11]:
df["NOMBRE DE CHAMBRES"] = df["NOMBRE DE CHAMBRES"].astype(float)
df["NOMBRE D'EMPLACEMENTS"] = df["NOMBRE D'EMPLACEMENTS"].astype(float)
df["CAPACITÉ D'ACCUEIL (PERSONNES)"] = df["CAPACITÉ D'ACCUEIL (PERSONNES)"].astype(float)

In [12]:
df["NOMBRE DE CHAMBRES"] = df["NOMBRE DE CHAMBRES"].replace(np.NaN, df["NOMBRE DE CHAMBRES"].mean()).astype(int)
df["NOMBRE D'EMPLACEMENTS"] = df["NOMBRE D'EMPLACEMENTS"].replace(np.NaN, df["NOMBRE DE CHAMBRES"].mean()).astype(int)

In [13]:
import sklearn 
from sklearn.preprocessing import LabelEncoder

In [14]:
lb_make = LabelEncoder()
df["TYPOLOGIE ÉTABLISSEMENT_code"] = lb_make.fit_transform(df["TYPOLOGIE ÉTABLISSEMENT"])
df["NOM COMMERCIAL_code"] = lb_make.fit_transform(df["NOM COMMERCIAL"])
df["CL_code"] = lb_make.fit_transform(df["CLASSEMENT"])

In [15]:
df.dtypes

DATE DE CLASSEMENT                                        object
TYPOLOGIE ÉTABLISSEMENT                                   object
CLASSEMENT                                                object
CATÉGORIE                                                 object
MENTION (villages de vacances)                            object
NOM COMMERCIAL                                            object
ADRESSE                                                   object
CODE POSTAL                                               object
COMMUNE                                                   object
SITE INTERNET                                             object
TYPE DE SÉJOUR                                            object
CAPACITÉ D'ACCUEIL (PERSONNES)                           float64
NOMBRE DE CHAMBRES                                         int32
NOMBRE D'EMPLACEMENTS                                      int32
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)     object
NOMBRE DE LOGEMENTS (vill

In [16]:
df["CLASSEMENT"] == "5 étoiles"

0        False
1        False
2        False
3        False
4        False
         ...  
21321    False
21322    False
21323    False
21324    False
21325    False
Name: CLASSEMENT, Length: 21304, dtype: bool

In [17]:
def numeric_classement(x):
    if x == "1 étoile":
        return 1
    elif x == "2 étoiles":
        return 2
    elif x == "3 étoiles":
        return 3
    elif x == "4 étoiles":
        return 4  
    else: #On a vu que la colonne df["CLASSEMENT"] n'a pas des valeurs nulls donc que le reste c'est le denier cas avec 4 étoiles 
        return 5
df["CLASSEMENT_code"] = df["CLASSEMENT"].apply(numeric_classement)

In [18]:
df.dtypes

DATE DE CLASSEMENT                                        object
TYPOLOGIE ÉTABLISSEMENT                                   object
CLASSEMENT                                                object
CATÉGORIE                                                 object
MENTION (villages de vacances)                            object
NOM COMMERCIAL                                            object
ADRESSE                                                   object
CODE POSTAL                                               object
COMMUNE                                                   object
SITE INTERNET                                             object
TYPE DE SÉJOUR                                            object
CAPACITÉ D'ACCUEIL (PERSONNES)                           float64
NOMBRE DE CHAMBRES                                         int32
NOMBRE D'EMPLACEMENTS                                      int32
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)     object
NOMBRE DE LOGEMENTS (vill

In [19]:
df.isnull().sum()

DATE DE CLASSEMENT                                           0
TYPOLOGIE ÉTABLISSEMENT                                      0
CLASSEMENT                                                   0
CATÉGORIE                                                15357
MENTION (villages de vacances)                           21074
NOM COMMERCIAL                                               0
ADRESSE                                                      0
CODE POSTAL                                                  1
COMMUNE                                                     15
SITE INTERNET                                              294
TYPE DE SÉJOUR                                           20764
CAPACITÉ D'ACCUEIL (PERSONNES)                               0
NOMBRE DE CHAMBRES                                           0
NOMBRE D'EMPLACEMENTS                                        0
NOMBRE D'UNITES D'HABITATION (résidences de tourisme)    19755
NOMBRE DE LOGEMENTS (villages de vacances)             

In [20]:
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor


from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [21]:
target_column = ["CLASSEMENT_code"] 
predictors = ["TYPOLOGIE ÉTABLISSEMENT_code", "NOM COMMERCIAL_code", "CAPACITÉ D'ACCUEIL (PERSONNES)", "NOMBRE DE CHAMBRES", "NOMBRE D'EMPLACEMENTS" ]
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min  \
CAPACITÉ D'ACCUEIL (PERSONNES)  21304.0  0.023390  0.036980  0.000099   
NOMBRE DE CHAMBRES              21304.0  0.038808  0.034856  0.002745   
NOMBRE D'EMPLACEMENTS           21304.0  0.026474  0.032505  0.000788   
TYPOLOGIE ÉTABLISSEMENT_code    21304.0  0.236810  0.224185  0.000000   
NOM COMMERCIAL_code             21304.0  0.493231  0.283416  0.000000   
CL_code                         21304.0  1.893729  0.864022  0.000000   
CLASSEMENT_code                 21304.0  2.891898  0.858480  1.000000   

                                     25%       50%       75%  max  
CAPACITÉ D'ACCUEIL (PERSONNES)  0.005221  0.011131  0.027581  1.0  
NOMBRE DE CHAMBRES              0.022873  0.038426  0.038426  1.0  
NOMBRE D'EMPLACEMENTS           0.016548  0.016548  0.016548  1.0  
TYPOLOGIE ÉTABLISSEMENT_code    0.000000  0.250000  0.250000  1.0  
NOM COMMERCIAL_code             0.245812  0.483958  0.732693  1.0  
CL_code                         1.000000  2.000000  2.000000  5.0  
CLASSEMENT_code                 2.000000  3.000000  3.000000  5.0

In [22]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(14912, 5)
(6392, 5)


In [23]:
print(predictors)

['TYPOLOGIE ÉTABLISSEMENT_code', 'NOM COMMERCIAL_code', "CAPACITÉ D'ACCUEIL (PERSONNES)", 'NOMBRE DE CHAMBRES', "NOMBRE D'EMPLACEMENTS"]


In [30]:
mlp = MLPClassifier(hidden_layer_sizes=(500,200,50), activation='relu', solver='adam', max_iter=500)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

C:\Users\Lily Huong\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [31]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[  56  237  248   26    0]
 [  21 2075 1955  143    2]
 [   9 1424 5184  392    2]
 [   7  271 1489  850    3]
 [   3   65  259  147   44]]
              precision    recall  f1-score   support

           1       0.58      0.10      0.17       567
           2       0.51      0.49      0.50      4196
           3       0.57      0.74      0.64      7011
           4       0.55      0.32      0.41      2620
           5       0.86      0.08      0.15       518

    accuracy                           0.55     14912
   macro avg       0.61      0.35      0.37     14912
weighted avg       0.56      0.55      0.53     14912



In [29]:
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[  28   92  117    6    0]
 [  17  758  951   44    0]
 [  10  536 2281  137    0]
 [   1  122  787  285    8]
 [   1   21  108   68   14]]
              precision    recall  f1-score   support

           1       0.49      0.12      0.19       243
           2       0.50      0.43      0.46      1770
           3       0.54      0.77      0.63      2964
           4       0.53      0.24      0.33      1203
           5       0.64      0.07      0.12       212

    accuracy                           0.53      6392
   macro avg       0.54      0.32      0.35      6392
weighted avg       0.53      0.53      0.49      6392

